---

name: Regression
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    name: Run CAD flow tests

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/siliconcompiler/sc_runner:latest

    env:
      GIT_TOKEN: ${{ secrets.ZA_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup permissions
        run: |
          apt update && apt install sudo -y
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

          echo ${{ secrets.ZA_TOKEN }} | gh auth login --with-token
          gh auth setup-git

      - name: Setup git access
        run: |
          git config --global --add url."https://github.com/".insteadOf git@github.com:

      - name: Setup python
        run: |
          python3 -m venv --system-site-packages .efpga
          . .efpga/bin/activate
          python3 -m pip install --upgrade pip
          pip3 install -e .[test]

      - name: Run tests
        run: |
          . .efpga/bin/activate
          pytest
